config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('subjects/', include('subjects.urls', namespace='subjects.subjects')),
    path('classboard/', include('classboard.urls')),
    path('students/', include('students.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('testimonials/', include('testimonials.urls', namespace='testimonials.testimonials')),
    path('articles/', include('articles.urls', namespace='articles.articles')),
    path('search/', include('site_searches.urls', namespace='site_searches.search')),


    path("accounts/", include("django.contrib.auth.urls")),
    path("login/", auth_views.LoginView.as_view(template_name = "login.html"), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

testimonials/urls.py
from django.urls import path
from .views import (
    TestimonialCreateView,
    TestimonialUpdateView,
    TestimonialDeleteView,
    TestimonialListViews,
)

app_name = "testimonials"

urlpatterns = [
    path("", TestimonialListViews.as_view(), name="testimonials_list"),
    path("create/", TestimonialCreateView.as_view(), name="testimonials_create"),
    path(
        "<int:pk>/update/", TestimonialUpdateView.as_view(), name="testimonials_update"
    ),
    path(
        "<int:pk>/delete/", TestimonialDeleteView.as_view(), name="testimonials_delete"
    ),
]

wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    path('', show_teachers_grid, name='show_teachers_grid'),
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

testimonials/models.py
from django.db import models
from persons.models import PersonAbstract

from site_searches.managers import SearchManagerTestimonials

# Create your models here.


class Testimonial(PersonAbstract):
    title = models.CharField(verbose_name="Заголовок", max_length=150)
    testimonial = models.TextField(verbose_name="Отзыв")
    created_at = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Дата обновления", auto_now=True)
    active = models.BooleanField(verbose_name="Активен", default=False)

    objects = SearchManagerTestimonials()

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        ordering = ["first_name", "last_name"]

    def __str__(self) -> str:
        return f"{self.title}"

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("testimonials:testimonials_list")

testimonials/forms.py
from django import forms
from .models import Testimonial

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ('title', 'first_name', 'last_name', 'email', 'phone', 'image', 'testimonial',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 
                                            'placeholder': 'Заголовок отзыва', 
                                            'required': 'required'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 
                                             'required': 'required'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'label': 'Изображение'}),
            'testimonial': forms.Textarea(attrs={
                                                'class': 'form-control', 
                                                'required': 'required',
                                                'placeholder': 'Оставьте Ваш отзыв'
                                                }),
        }

testimonials/views.py
from django.shortcuts import render
from  django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic import CreateView, UpdateView, DeleteView, ListView 
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Testimonial
from .forms import TestimonialForm

# Create your views here.

class TestimonialListViews(LoginRequiredMixin, ListView):
    model = Testimonial
    template_name = 'testimonials/testimonials_list.html'
    context_object_name = 'testimonials'

class TestimonialCreateView(CreateView):
    model = Testimonial
    template_name = 'testimonials/testimonial_form.html'
    success_url = reverse_lazy('mainpage:mainpage')
    form_class = TestimonialForm

class TestimonialUpdateView(LoginRequiredMixin, UpdateView):
    model = Testimonial
    template_name = 'testimonials/testimonial_form.html'
    success_url = reverse_lazy('testimonials:testimonials_list')
    form_class = TestimonialForm

class TestimonialDeleteView(LoginRequiredMixin, DeleteView):
    model = Testimonial
    template_name = 'testimonials/testimonial_confirm_delete.html'
    success_url = reverse_lazy('testimonials:testimonials_list')

templates/testimonials/testimonial_confirm_delete.html
{% extends 'layout/base.html' %}


{% block title %}
    Удалить {{ object }}
{% endblock title %}
    


{% block content %}
    <form method="post" action="{% url 'testimonials:testimonials_delete' object.pk %}">
        {% csrf_token %}
        <h3>Вы уверены, что хотите удалить отзыв {{ object }}?</h3>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'testimonials:testimonials_list' %}" class="btn btn-primary">Отмена</a>
    </form>
    
{% endblock content %}

templates/testimonials/testimonial_form.html
{% extends 'layout/base.html' %}


{% block title %}
    Редактировать отзыв
{% endblock title %}
    

{% block content %}
<div class="container-xxl py-5 wow fadeInUp mb-3 mt-3 ps-5 pe-5 row" data-wow-delay="0.1s">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Отправить</button>
        <a href="{% url 'testimonials:testimonials_list' %}" class="btn btn-secondary">Назад</a>
    </form>
</div>
{% endblock content %}
    

templates/testimonials/testimonials_list.html
{% extends 'layout/base.html' %} 
{% block title %} Отзывы {% endblock title %}
{% block content %}
<table class="mb-3 mt-3 table table-info table-striped">
  <thead>
    <th>Отзыв</th>
    <th>Автор</th>
    <th>Активен</th>
    <th>Дата создания</th>
    <th>Дата изменения</th>
    <th>Действия</th>
  </thead>
  <tbody>
    {% for testimonial_item in testimonials %}
    <tr>
      <td>
        <a
          href="{% url 'testimonials:testimonials_update' testimonial_item.pk %}"
          >{{ testimonial_item.title }}</a
        >
      </td>
      <td>
        {{ testimonial_item.first_name }} {{ testimonial_item.last_name }}
      </td>
      <td>{{ testimonial_item.active }}</td>
      <td>{{ testimonial_item.create_at }}</td>
      <td>{{ testimonial_item.update_at }}</td>
      <td><a href="{% url 'testimonials:testimonials_delete' testimonial_item.pk %}">Удалить</a></td>
    </tr>

    {% endfor %}
  </tbody>
</table>

{% endblock content %}