articles/urls.py
from django.urls import path
from .views import ArtticlesListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, CommentCreateView

app_name = 'articles'

urlpatterns = [
    path('', ArtticlesListView.as_view(), name='articles_list'),
    path('<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('subjects/', include('subjects.urls', namespace='subjects.subjects')),
    path('classboard/', include('classboard.urls')),
    path('students/', include('students.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('testimonials/', include('testimonials.urls', namespace='testimonials.testimonials')),
    path('articles/', include('articles.urls', namespace='articles.articles')),
    path('search/', include('site_searches.urls', namespace='site_searches.search')),


    path("accounts/", include("django.contrib.auth.urls")),
    path("login/", auth_views.LoginView.as_view(template_name = "login.html"), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    path('', show_teachers_grid, name='show_teachers_grid'),
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

articles/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _
from site_searches.managers import SearchManagerArticles, SearchManagerComments


class Article(models.Model):
    author = models.ForeignKey(
        verbose_name="Автор", to="auth.User", on_delete=models.CASCADE
    )
    title = models.CharField(verbose_name="Заголовок", max_length=256)
    slug = models.SlugField(verbose_name="slug")
    text = models.TextField(verbose_name="Содержание")
    image = models.ImageField(verbose_name="Изображение", upload_to="articles/")
    created_at = models.DateTimeField(verbose_name="Создано", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Изменено", auto_now=True)

    objects = SearchManagerArticles()

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    def __str__(self) -> str:
        return f"{self.title}"

    def save(self, *args, **kwargs):
        self.slug = slugify(_(self.title))
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("articles:article_detail", kwargs={"pk": self.pk})

# Comment
class Comment(models.Model):
    article = models.ForeignKey(
        verbose_name="Статья", to="articles.Article", on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        verbose_name="Автор",
        to="auth.User",
        on_delete=models.CASCADE,
        default=None,
        blank=True,
        null=True,
    )
    text = models.TextField(verbose_name="Комментарий")
    created_at = models.DateTimeField(verbose_name="Создано", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Изменено", auto_now=True)

    objects = SearchManagerComments()

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self) -> str:
        return f"{self.author.username} - {self.article[:40]}"

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("articles:article_detail", kwargs={"pk": self.article.pk})

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'text', 'image', 'author')
        labels = {
            'title': 'Название',
            'text': 'Текст',
            'image': 'Изображение',
            'author': 'Автор',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('text', )
        labels = {
            'text': 'Комментарий',
        }
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }

articles/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .forms import ArticleForm, CommentForm
from .models import Article, Comment

from icecream import ic

# Create your views here.


class ArtticlesListView(ListView):
    model = Article
    template_name = "articles/articles_list.html"
    context_object_name = "articles"
    paginate_by = 10


class ArticleDetailView(DetailView):
    model = Article
    template_name = "articles/article_detail.html"
    context_object_name = "article"
    succes_url = reverse_lazy("articles:articles_list")
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class

        # if self.request.user.is_authenticated:
        context["comments"] = Comment.objects.filter(article=self.get_object())
        return context

    def post(self, request, *args, **kwargs):
        new_comment = Comment(
            text=request.POST.get("text"),
            author=request.user,
            article=self.get_object(),
        )

        new_comment.save()
        return self.get(request, *args, **kwargs)

class ArticleCreateView(CreateView):
    model = Article
    template_name = "articles/article_from.html"
    success_url = reverse_lazy("articles:articles_list")
    form_class = ArticleForm


class ArticleUpdateView(UpdateView):
    model = Article
    template_name = "articles/article_from.html"
    success_url = reverse_lazy("articles:articles_list")
    form_class = ArticleForm


class ArticleDeleteView(DeleteView):
    model = Article
    template_name = "articles/article_delete.html"
    success_url = reverse_lazy("articles:articles_list")


class CommentCreateView(CreateView):
    model = Comment
    template_name = "articles/comment_from.html"
    success_url = reverse_lazy("articles:articles_list")
    form_class = CommentForm

templates/articles/article_delete.html
{% extends 'layout/base.html' %}


{% block title %}
    Удалить {{ object }}
{% endblock title %}
    


{% block content %}
<section class="py-5 text-center">
<div class="container-xxl py-5 wow fadeInUp mb-5 mt-5 pl-10 pr-10"  data-wow-delay="0.1s">
    <form method="post" action="{% url 'articles:article_delete' object.pk %}">
        {% csrf_token %}
        <h3>Вы уверены, что хотите удалить статью: "{{ object }}"?</h3>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'articles:articles_list' %}" class="btn btn-primary">Отмена</a>
    </form>
    </div>
    </section>
    
{% endblock content %}

templates/articles/article_detail.html
{% extends 'layout/base.html' %}


{% block title %}
    {{ object }}
{% endblock title %}

{% block content %}
        <!-- About Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="row g-5">
                    <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s" style="min-height: 400px;">
                        <div class="position-relative h-100">
                            <img class="img-fluid position-absolute w-100 h-100" src="{{ article.image.url}}" alt="" style="object-fit: cover;">
                        </div>
                    </div>
                    <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.3s">
                        <h6 class="section-title bg-white text-start text-primary pe-3">{{ article.updated_at|date:"d-M-Y"}}|{{ article.author }}</h6>
                        <h1 class="mb-4">{{ article.title }}</h1>
                        <p class="mb-4">{{ article.text }}</p>
                        <a class="btn btn-primary py-3 px-5 mt-2" href="{% url 'articles:articles_list' %}">Назад</a>
                    </div>
                    
                </div>
            </div>
        </div>
        <!-- About End -->
        {% if user.is_authenticated %}

            <div class="container-xxl py-5">
                <div class="container">
                    <div class="row g-5">
                        <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s" style="min-height: 400px;">
                            <form action="" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" class="btn btn-primary py-3 px-5 mt-2" value="Отправить">
                        </form>
                        </div>
                    </div>
                </div>
            </div>
                    
        {% endif %}

        
        <ul>
            {% for comment_item in comments %}
            <li>           
             <div>
                <span>
                  <strong class="text-info">{{ comment_item.author }} </strong>
                  <small class="text-muted">{{ comment_item.update_at }}</small>
                </span>
                <p>
                  {{ comment_item.text|safe }}
                </p>
              </div>
            </li>
            {% endfor %}
        </ul>
            
{% endblock content %}

templates/articles/article_from.html
{% extends 'layout/base.html' %} 

{% block title %} Создать, обновить статью {% endblock title %} 

{% block content %}
<section class="py-5">
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">{{ form.as_p }}</div>
  <button type="submit" class="btn btn-info">Отправить</button>
  <a class="btn btn-primary" href="{% url 'articles:articles_list' %}">Обратно</a>
</form>
</section>
{% endblock content %}

templates/articles/articles_list.html
{% extends 'layout/base.html' %} 

{% block title %} Создать, обновить статью {% endblock title %} 

{% block content %}
    <section class="py-5">
    {% for article_item in articles %}
        <span class="border border-success">  Автор: {{ article_item.author }} </span>
        <span class="border border-warning">Дата: 
        {% if article_item.created_at == article_item.updated_at  %}
            {{ article_item.created_at|date:"d-M-Y" }} 
        {% else %}
            {{ article_item.updated_at|date:"d-M-Y" }}                                                      
        {% endif %}
        </span>
        <div class="col-12">
            <img src="{{ article_item.image.url}}" alt="{{ article_item.title }}" width="70" height="50" class="border rounded-circle p-2 mx-auto mb-3">
            {{ article_item.title }}
        </div>

        <div class="table align-items-center">
            <a class="btn border-warning" href="{% url 'articles:article_detail' article_item.pk %}">Читать</a> 
            {% if user.is_authenticated %}
            <a class="btn btn-secondary" href="{% url 'articles:article_update' article_item.pk %}">Обновить</a> 
            <a class="btn btn-danger" href="{% url 'articles:article_delete' article_item.pk %}">Удалить</a>
            {% endif %}
        </div>

        
        {% if not forloop.last %}
            <hr>
            
        {% endif %}
            
           
    {% empty %}
        <h3 class="mt-5 ps-3 pe-3 text-center">На данной странице пока нет статей</h3>        
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Первый</a>
                <a href="?page={{ page_obj.previous_page_number }}">Обратно</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Последний</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Следующий &raquo;</a>
            {% endif %}
        </span>
    </div>
</section>
        
        
{% endblock content %}